include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    empty_constructor_bodies: true
    no_leading_underscores_for_local_identifiers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
